(in-package #:dwcalgorithms)

(5am:def-suite interval-suite :description "Interval Test Suite")
(5am:in-suite interval-suite)

(5am:test interval-<=>
  (5am:is (= -1 (<=> (make-interval 1 3)
                     (make-interval 2 4))))
  (5am:is (= -1 (<=> (make-interval 1 3)
                     (make-interval 1 5))))
  (5am:is (= 0 (<=> (make-interval 1 3)
                    (make-interval 1 3))))
  (5am:is (= 1 (<=> (make-interval 1 3)
                    (make-interval 0 5))))
  (5am:is (= 1 (<=> (make-interval 2 4)
                    (make-interval 1 3)))))

(5am:test interval-overlaps?
  (5am:is (overlap? (make-interval 1 3)
                    (make-interval 2 3)))
  (5am:is (overlap? (make-interval 2 3)
                    (make-interval 1 3)))
  (5am:is (overlap? (make-interval 1 3)
                    (make-interval 2 4)))
  (5am:is (overlap? (make-interval 1 3)
                    (make-interval 1 2)))
  (5am:is (overlap? (make-interval 5 10)
                    (make-interval 7 12)))
  (5am:is (overlap? (make-interval 7 12)
                    (make-interval 5 10)))
  (5am:is (not (overlap? (make-interval 2 3)
                         (make-interval 4 5))))
  (5am:is (not (overlap? (make-interval 4 5)
                         (make-interval 2 3)))))

(5am:test interval-search-test
  (let ((tree (make-instance 'avl-tree)))
    (insert tree (make-interval 1 3))
    (insert tree (make-interval 5 7))
    (insert tree (make-interval 9 11))
    (insert tree (make-interval 13 15))
    (insert tree (make-interval 17 19))
    (insert tree (make-interval 21 23))
    (insert tree (make-interval 25 27))
    (5am:is (=? #'<=> (make-interval 1 3) (interval-search tree (make-interval 2 3))))
    (5am:is (=? #'<=> (make-interval 25 27) (interval-search tree (make-interval 24 26))))
    (let ((found (interval-search tree (make-interval 8 14))))
      (5am:is (or (=? #'<=> found (make-interval 9 11))
                  (=? #'<=> found (make-interval 13 15)))))
    (5am:is (not (interval-search tree (make-interval -1 0))))
    (5am:is (not (interval-search tree (make-interval 100 102))))

    (5am:is (make-interval 25 27) (search tree (make-interval 25 27)))))
